// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bedkwsdxonsoapckwibw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZGt3c2R4b25zb2FwY2t3aWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzg2NjIsImV4cCI6MjA3Mzc1NDY2Mn0.eF4dg6J1NaIXsN9Y9o6njMqIK4Oli6lEpXpTvx_GYtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});